### PR TITLE
add Doom Emacs default LSP -mode config

### PR DESCRIPTION
**Pull request by savuori**

### CODE REVIEW

**Comment by jjlee** [comment]
Thanks, is there a reason why [lsp-rescript](https://github.com/jjlee/lsp-rescript) doesn't do what you want for Doom?

**Comment by savuori** [comment]
TBH, I skipped the normal Emacs setup once I saw the Doom -specific section and didn't read about that package. Is this closer to the recommended setup?

**Comment by jjlee** [comment]
Yes, thanks -- have you tested this configuration?  I don't use Doom but I'm happy to add example config if somebody has tried it.

**Comment by savuori** [comment]
I've now tested this on a couple of different machines and it seems to work =)

**Pull request merged**
